linters:
  enable:
    - revive

linters-settings:
  revive:
    max-open-files: 2048
    ignore-generated-header: true
    severity: error
    rules:
      - name: argument-limit
        arguments: [3]
      - name: deep-exit
      - name: defer
      - name: early-return
        arguments: ["preserveScope"]
      - name: empty-block
      - name: enforce-map-style
        arguments: ["make"]
      - name: filename-format
        arguments: ["^[_a-z][_a-z0-9]*\\.go$"]
      - name: function-result-limit
        arguments: [2]
      - name: import-shadowing
      - name: max-control-nesting
        arguments: [3]
      - name: nested-structs
      - name: range
      - name: struct-tag
      - name: unchecked-type-assertion
      - name: unreachable-code
      - name: use-any
